name: Keep Alive

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          curl -fLv https://fastapi-ci-cd-demo.onrender.com/
          echo "Ping sent at $(date)"